### ISSUE TITLE
Error in callback for watcher "config"

### ISSUE THREAD

**Issue by freimaks** [vue-bulma/datepicker#43] opened 2017-05-06 17:20 UTC
An error occurs when updating the page content:

```
[Vue warn]: Error in callback for watcher "config": 
(found in <Datepicker> at mydisk:\myproject\node_modules\vue-bulma-datepicker\src\index.vue
```

![image 6](https://cloud.githubusercontent.com/assets/26241659/25774526/2dbe7698-3299-11e7-8d09-98567b926358.png)

**Comment by beliolfa** [comment] 2017-05-06 19:31
It is caused by an error in index.vue.

There are two `methods` declarations, the last one overrides the first one.

**Comment by peteleco** [comment] 2017-05-06 19:38
There's two PR's [#38](https://github.com/vue-bulma/datepicker/pull/38) [#39](https://github.com/vue-bulma/datepicker/pull/39)  fixing this

**Comment by KKSzymanowski** [comment] 2017-05-07 03:02
Until @luventa merges the fix, it should work on v. 1.3.0 from March 6th.

**Comment by rcubitto** [comment] 2017-05-10 15:19
Is it possible to merge either of these PRs? It's a quick fix and it's affecting everyone.

**Comment by moonlik** [comment] 2017-05-16 07:16
@fundon @luventa please merge these PRs!

**Comment by AlbertClo** [comment] 2017-05-16 10:31
I have this problem too. I can confirm that the pull request solves the problem as well. Merge please :)

**Comment by FroeMic** [comment] 2017-05-19 21:51
Yeah, please merge one of these PRs 💃

**Comment by KKSzymanowski** [comment] 2017-05-20 00:10
@fundon @luventa I understand it's open source, you're doing it for free and I'm in no position to demand active participation, but please just hit the damn Merge button.

**Comment by luventa** [comment] 2017-06-01 09:02
Yes sir, pr has been merged and new version is just published. 😢

**Closed as completed by luventa** 2017-06-01 09:02 UTC
